<P>
A TCLUG beer meeting is a weekly get-together where TCLUG members can get to know one another and share a beer. The beer meetings are open to anyone and everyone, so don't be afraid to show up.
<P>
<B>When:
<BR></B> Thursday, January 25th, 6pm - 8pm
<P>
<B>Where:</B>
<BR>
Jake's Sports Cafe, New Brighton
<BR>
790 W County Rd D
<BR>
New Brighton, MN 55112-3509
<BR>
(651) 636-2901
<P>
<A HREF="http://twincities.citysearch.com/map?mode=geo&lat=450358&lon=-931973&id=5529287&fid=2" TARGET="map">Click here for a map</A>

<BR>
Hope to see you there!
<P>

