<UL><LI><b>Thursday, February 5th, 2001, 6pm - 8pm</b></LI>
<blockquote>
<A HREF="/beermeeting/">Twin Cities Linux Users Group Beer Meeting</A>
</blockquote>

<LI><b>Monday, February 12, 2001, 7pm</b></LI>
<blockquote>
<A HREF="http://www.ima.umn.edu/multimedia/winter/NLDC.jpg">The Folly of Copy Protection on the Internet - By Bruce Schneier</A>
</blockquote>

<LI><b>Saturday, March 3rd, 2001, 10am - 5pm</b></LI>
<blockquote>
<A HREF="/installfest/">Twin Cities Linux Users Group Installfest</A>
<br>
</blockquote>

<LI><b>Saturday, March 24th, 2001, noon - 4pm</b></LI>
<blockquote>
<A HREF="http://www.k-lug.com/demoday/">K-LUG Linux Demo Day</A>
<br>
</blockquote>

<LI><b>Saturday, April 7th, 2001, noon - 2pm</b></LI>
<blockquote>
Twin Cities Linux Users Group Meeting - High Availability Clustering for Linux by SteelEye (<A HREF="http://www.steeleye.com">www.steeleye.com</A>)
<br>
</blockquote>

<LI><b>Thursday, April 12th, 2001, 10am - 5pm</b></LI>
<blockquote>
Linux Conference (more info coming soon)
<br>
</blockquote>

<LI><b>Saturday, May 5, 2001, noon - 2pm</b></LI>
<blockquote>
Twin Cities Linux Users Group Meeting - OpenNMS (<A HREF="http://www.opennms.org">www.opennms.org</A>)
<br>
</blockquote>

<LI><b>May 23rd & 24th, 2001</b></LI>
<blockquote>
The TCLUG will be at the <A HREF="http://www.strictlyebusiness.net/strictlyebusiness/mpls/main_mpls.po">Strictly e-Business Solutions Expo</A>
<br>
</blockquote>

<LI><b>Saturday, June 2nd, 2001</b></LI>
<blockquote>
Twin Cities Linux Users Group Meeting - qmail
<br>
</blockquote>

</UL>
