<CENTER>
<a href="#tclug">TCLUG Links of Interest</a> &#124;
<a href="#news">News</a> &#124;
<a href="#apps">Applications</a> &#124;
<a href="#docs">Documentation</a> &#124;
<a href="#distribs">Distributions</a> &#124;
<a href="#hardware">Hardware Compatibility</a>
</center>

<H4><a name="tclug">TCLUG Links of Interest</a></h4>

<UL>
<LI><a href="http://www.materialsprocessing.com/surplus.html">MPC Surplus Store</a></li>
<LI><a href="http://www.nanosys1.com">General Nanosystems</a></li>
</ul>



<H4><a name="news">Linux News</a></h4>

<UL>
<LI><a href="http://www.linux.com/">Linux.com</a></li>
<LI><a href="http://www.linux.org/">Linux.org</a></li>
<LI><a href="http://www.linuxhq.com/">Linux Headquarters</a></li>
<LI><a href="http://www.linuxjournal.com/">Linux Journal</a></li>
<LI><a href="http://www.linuxtoday.com">Linux Today</a></li>
<LI><a href="http://lwn.net/">Linux Weekly News</a></li>
<LI><a href="http://www.linuxplanet.org/">Linux Planet</a></li>
<LI><a href="http://slashdot.org/">Slashdot</a></li>
</ul>


<H4><a name="apps">Linux Applications</a></h4>

<UL>
<LI><a href="http://www.freshmeat.net/">Freshmeat</a></li>
<LI><a href="http://www.gnome.org/">GNOME</a></li>
<LI><a href="http://www.kde.org/">KDE</a></li>
<LI><a href="http://www.xnet.com/~blatura/linapps.shtml">Linux Applications
and Utilities Page</a></li>
<LI><a href="http://www.linuxapps.com/">Linux Apps</a></li>
<LI><a href="http://linas.org/linux/index.html">Linux Enterprise
Computing</a></li>
<LI><a href="http://www.plig.org/xwinman/">Window Managers</a></li>
</ul>

<H4><a name="docs">Linux Documentation</a></h4>

<UL>
<LI><a href="http://tldp.org/">The Linux Documentation Project</a>--A
complete and searchable archive of the official FAQs, HOWTOs, and
mini-HOWTOs.</li>
</ul>

<H4><a name="distribs">Linux Distributions</a></h4>
<UL>
<LI><a href="http://www.redhat.com">RedHat</a></LI>
<LI><A HREF="http://www.linux-mandrake.com">Mandrake</A></LI>
<LI><A HREF="http://www.debian.org">Debian</A></LI>
<LI><A HREF="http://www.suse.com">SuSE</A></LI>
<LI><A HREF="http://www.slackware.com">Slackware</A></LI>



</ul>

<H4><a name="hardware">Linux Hardware Compatability Quick Reference</a></h4>

<P>In general, all distributions can support the same hardware.  The separate
lists below are distribution specific, however, since each can include
specific software packages for use with specific hardware that may not be
included with the other distributions.</p>

<UL>
<LI><a href="http://www.tldp.org/HOWTO/Hardware-HOWTO/index.html">LDP Hardware Compatability
HOWTO</a>: Use for Debian, Slackware and others.</li>
<LI><a
href="http://www.redhat.com/support/hardware/intel/62/rh6.2-hcl-i.ld.html">Red
Hat's Hardware Compatability Database</a></li>
<LI><a
href="http://cdb.suse.de/cgi-bin/scdb?HTML=ENGLISH/cdb_listtemplates/menu.htm&LANG=ENGLISH">SuSE
Hardware Compatability Database</a></li>
<LI><a href="http://www.linux-mandrake.com/en/fhard.php3">Mandrake Hardware
Compatability List</a></li>
</ul>

