<P>
<TABLE border=0 align=center valign=top cellpadding=0 cellspacing=0>
<TR><TD valign="top">
        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">
                <B>News</B><BR>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD>
                        <A HREF="http://slashdot.org">Slashdot</A></TD><TD> - News for Nerds, Stuff that matter</TD></TR>
                        <TR><TD><A HREF="http://lwn.net/daily/">Linux Daily News</A></TD><TD> - Daily Linux-related News</TD></TR>
                        <TR><TD><A HREF="http://news.tucows.com/ext2/">Ext2</A></TD><TD> - The monthly web magazine for Linux Users</TD></TR>
                        <TR><TD><A HREF="http://linuxtoday.com/">Linux Today</A></TD><TD> - Another Linux news site</TD></TR>
                        <TR><TD><A HREF="http://32bitsonline.com/">32bitsOnline</A></TD><TD> - A lot of great articles</TD></TR> 
                </TABLE>
                </TD></TR>
        </TABLE>


</TD></TR><TR><TD valign="top">
        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">
                <B>Distributions</B><BR>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD>
                        <A HREF="http://www.redhat.com">Redhat</A></TD>
                        </TD><TD> - A great all-around distribution</TD>
                        </TR><TR><TD>
                        <A HREF="http://www.linux-mandrake.com">Mandrake</A></TD>
                        <TD> - Basically RedHat optimized for Pentiums</TD></TR><TR><TD>
                        <A HREF="http://www.caldera.com">Caldera</A></TD>
                        <TD> - The perfect business solution</TD>
                        </TR><TR><TD>
                        <A HREF="http://www.debian.org">Debian</A></TD>
                        <TD> - A very full (comes with over 2250 packages) distribution</TD>
                        </TR><TR><TD>
                        <A HREF="http://www.suse.com">SuSE</A></TD>
                        <TD> - Another great distribution</TD>
                        </TR><TR><TD>
                        <A HREF="http://www.slackware.com">Slackware</A></TD>
                        <TD> - The only distribution for the true hacker</TD>
                        </TR>
                </TABLE>
                </TD></TR>
        </TABLE>


</TD></TR><TR>
<TD valign="top">
        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">
                <B>Software</B>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD>
                        <A HREF="http://www.linuxiso.org/">Fresh iso images</A></TD>
                        <TD> - Just like Mom used to burn.</TD>
                        </TR>

                        <TR><TD>
                        <A HREF="http://rufus.w3.org">RPM Repository on rpmfind.net</A></TD>
                        <TD> - All the RPM's you could ever want</TD>
                        </TR>

                        <TR><TD width="140">
                        <A HREF="http://mn.us.mirrors.freshmeat.net">Freshmeat</A></TD>
                        <TD> - All the latest apps</TD>
                        </TR>

                        <TR><TD width="140">
                        <A HREF="http://www.appwatch.com">Appwatch</A></TD>
                        <TD> - All the latest apps</TD>
                        </TR>


                        <TR><TD>
                        <A HREF="http://fishnet.linuxberg.com/">Linuxberg</A></TD>
                        <TD> - All the latest apps</TD>
                        </TR><TR><TD>
                        <A HREF="http://www.linuxapps.com/">Linuxapps</A></TD>
                        <TD> - All the latest apps</TD>
                        </TR>
                </TABLE>
                </TD></TR>
        </TABLE>

</TD></TR>
<TR><TD valign="top">
        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">

                <B>Help and Linux References</B>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD>
                        <A HREF="http://www.linuxnovice.org">LinuxNovice.org</A></TD>
                        <TD> - The name says it all</TD></TR>
                        <TR><TD>
                        <A HREF="http://www.linux.org">Linux Online</A></TD>
                        <TD> - A great starting place for beginners</TD></TR>
                        <TR><TD>
                        <A HREF="http://linux.com">Linux.com</A></TD>
                        <TD> - brought to you by VA Linux Systems</TD></TR>
                        <TR><TD>
                        <A HREF="http://LinuxStart.com">LinuxStart</A></TD>
                        <TD> - A Linux Web Portal</TD></TR>
                        <TR><TD>
                        <A HREF="http://JustLinux.com">JustLinux</A></TD>
                        <TD> - Another Linux Web Portal</TD></TR>
                        <TR><TD>
                        <A HREF="http://heaven.hamline.edu/LDP">Linux Documentation Project</A></TD>
                        <TD> - All the Linux info you could ever want</TD></TR>
                        <TR><TD><A HREF="http://www.linuxhardware.net">Linux Hardware.net</A></TD>
                        <TD> - Review of hardware performace under Linux</TD><TD>
                </TABLE>
                </TD></TR>
        </TABLE>

</TD></TR><TR>
<TD valign="top">

        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">
                <B>X Windows</B>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD>
                        <A HREF="http://www.xfree86.org">XFree86.org</A></TD>
                        <TD> - The ones who make it all possible</TD>
                        </TR><TR>
                        <TD>
                        <A HREF="http://xwindows.org">xwindows.org</A></TD>
                        <TD> - A central resource for all things X</TD>
                        </TR><TR>
                        <TD>
                        <A HREF="http://www.windowmaker.org/">Windowmaker</A></TD>
                        <TD> - The look and feel of the NeXTStep interface</TD>
                        </TR><TR>
                        <TD>
                        <A HREF="http://www.enlightenment.org">Enlightenment</A></TD>
                        <TD> - Rasterman and Mandrake hard at work</TD>
                        </TR><TR>
                        <TD>
                        <A HREF="http://www.afterstep.org/">Afterstep</A></TD>
                        <TD> - A lot like WindowMaker, but different</TD>
                        </TR><TR>
                        <TD>
                        <A HREF="http://www.gnome.org">Gnome</A></TD>
                        <TD> - The GNU Network Object Model Environment</TD>
                        </TR><TR>
                        <TD>
                        <A HREF="http://www.kde.org">KDE</A></TD>
                        <TD> - The K Desktop Environment</TD>
                        </TR>
                </TABLE>
                </TD></TR>
        </TABLE>
</TD></TR><TR><TD valign="top">

        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">
                <B>User Groups</B>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD>
                        <A HREF="http://www.uum.org/">UUM</A></TD><TD> - Unix Users of Minnesota</TD></TR>
                        <TR><TD><A HREF="http://www.scalug.org/">SCALUG</A></TD><TD> - St. Cloud Linux Users Group</TD></TR>
                        <TR><TD><A HREF="http://k-lug.com/">K-LUG</A></TD><TD> - Rochester Linux Users Group</TD></TR>
                        <TR><TD><A HREF="http://www.fllux.org">FLLUX</A></TD><TD> - Forest Lake Linux Users Xchange</TD></TR>
                        </TABLE>
                </TABLE>

</TD></TR><TR><TD valign="top">

        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">
                <B>Magazines</B>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD>
                        <A HREF="http://linuxjournal.com/">The Linux Journal</A></TD><TD> - The original Linux Magazine</TD></TR>
                        <TR><TD><A HREF="http://www.linux-mag.com/">Linux Magazine</A></TD><TD> - More technical than the LJ</TD></TR>
                        </TABLE>
                </TABLE>

</TD></TR><TR><TD valign="top">

        <TABLE>
                <TR><TD>
                <FONT COLOR="#FFFFFF">
                <B>IP Masquerading</B>
                </FONT>
                </TD></TR>
                <TR><TD>
                <TABLE>
                        <TR><TD width="140">
                        <A HREF="http://howto.real-time.com/realtime/PortForwarding/tclugpres/">IP PortForwarding HOWTO</A></TD><TD> - Amy Tanner's PortForwading presentation from the September TCLUG meeting</TD></TR>
                        <TR><TD><A HREF="http://heaven.hamline.edu/LDP/HOWTO/IPCHAINS-HOWTO.html">IPChains HOWTO</A></TD><TD> - More detail about IPChains</TD></TR>
                        <TR><TD><A HREF="http://members.home.net/ipmasq/">IP Masquerading Homepage</A></TD><TD> - A great resource with a lot of links</TD></TR>
                        <TR><TD><A HREF="http://www.psionic.com/abacus/portsentry/">PortSentry</A></TD><TD> - A great portscan detector</TD></TR>
                        </TABLE>
                </TABLE>


</TD></TR>

</TABLE>

