<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title><?php print "$title" ?></title>
<meta name="title" content="TCLUG - Twin Cities Linux Users Group" />
<meta name="description" content="The Twin Cities Linux User's Group is a
local Linux advocacy group dedicated to expanding the use of Linux, both
professionally and personally.  The group is comprised entirely of
volunteers." />
<meta name="keywords" content="twin cities linux users
group, linux, minnesota, advocacy, linux resources, linux links, mailing
list, local events, twin cities, lug, linux users group, installfest,
download linux, linux user group, linux usergroup, in minnesota, in twin
cities " />
<meta name="language" content="English" />
<meta name="author" content="TCLUG Webmaster" />
<meta name="robots" content="ALL" />
<meta name="revisit-after" content="30 days" />
<meta name="reply-to" content="webmaster@mn-linux.org" />
<meta name="document-class" content="Living Document" />
<meta name="document-classification" content="Computers" />
<meta name="document-rights" content="Public Domain" />
<meta name="document-type" content="Public" />
<meta name="document-rating" content="General" />
<meta name="document-distribution" content="Global" />
<meta name="document-state" content="Static" />
<meta http-equiv="author" content="TCLUG Webmaster">
<meta http-equiv="Reply-to" content="webmaster@mn-linux.org">
<meta http-equiv="Keywords" content="Twin Cities Linux Users Group, Linux, Minnesota,
Advocacy, Linux Resources, Linux Links, Mailing List, Local Events">
<meta http-equiv="Description" content="The Twin Cities Linux User's Group is a
local Linux advocacy group dedicated to expanding the use of Linux, both
professionally and personally.  The group is comprised entirely of
volunteers.">
<style>
body, center, form, hr, p, td, th { font-family: Helvetica,Verdana,Sans-Serif;
                     color: #000000;}

.header {       font-family: Helvetica,Verdana,sans-serif;
                        font-weight: bold;
                        color: #000080;}

.copy  {        font-family: Helvetica,Verdana,sans-serif;
                        color: #999999;}
</style>
<link REL="SHORTCUT ICON" HREF="/images/tclug.ico" >
</head>
<body bgcolor="white" background="" marginwidth="0" marginheight="0" topmargin="0" leftmargin="0">
