<b>What:</b>
<br>Twin Cities Linux Users Group Meeting
<br>
<p>
<b>When:</b>
<br>Wednesday, July 18, 2001 7-9pm
<p>
<b>Topic:</b>
<br>Borland Kylix</a>
<p>
<b>Where:</b>
<br>University of Minnesota
<br>West Bank Office Building(WBOB) grey w/ red trim
<br>1300 South 2nd Street
<br>Room 140
<br>Minneapolis, MN 55455
<br>Parking: Top Level of the Ramp 
<br><a href="http://www.tcnpa.homestead.com/">Directions</a>
