<BR><P>
<B>Past Meeting Presentations:</B>
<CENTER>
<TABLE border=0>
<TR><TD>
<LI>October 4th, 2003 -
</TD><TD>
An introduction to digital signatures, presented by Florin.<br>
<A HREF="digital_signatures.pdf">PDF</A><br>
<A HREF="digital_signatures.sxi">OpenOffice</A>
</TD></TR>
<TR><TD>
<LI>February 1st, 2003 -
</TD><TD>
<A HREF="http://www.sihope.com/~adamm/tclug/">Marvin: One Company's Solution to the Spam Problem, presented by Adam Maloney</A>
</TD></TR>
<TR><TD>
<LI>October 5th, 2002 -
</TD><TD>
<A HREF="http://www.hick.org/~raffi/tclug/">Scripting Languages Under the hood - Raphael Mudge</A>
</TD></TR>
<TR><TD>
<LI>April 6th, 2002 -
</TD><TD>
<A HREF="http://thinkunix.net/docs/editors/">Scot Jenkins talks about text editors</A>
</TD></TR>
<TR><TD>
<LI>March 2nd, 2002 -
</TD><TD>
<A HREF="http://thinkunix.net/docs/backup-overview/">Scot Jenkins talks about backups</A>
</TD></TR>
<TR><TD>
<LI>December 1st, 2001 -
</TD><TD>
<A HREF="http://www.codeweavers.com/about/news/talks/comdex2001/">Jeremy White from CodeWeavers, Inc - The state of Wine</A>
</TD></TR><TR><TD>
<LI>October 6th, 2001 -
</TD><TD>
<A HREF="http://www.socialmotors.com/TCLUG/procmail/">Marty McCarthy - Procmail</A>
</TD></TR><TR><TD>
<LI>August 4th, 2001 -
</TD><TD>
<A HREF="pastnotes/djbdns.pdf">Nate Straz - djbdns talk</A>
</TD></TR><TR><TD></TD><TD>
<A HREF="pastnotes/dns-08042001/">Scott Dier - Some DNS Topics</A>
</TD></TR><TR><TD>
<LI>July, 2001 -
</TD><TD>
<A HREF="pastnotes/dope_on_zope.pdf">Tim Wilson - Dope on Zope</A>
</TD></TR><TR><TD>
<LI>March 21st, 2001 -
</TD><TD>
<A HREF="pastnotes/dinosaur_and_penguin.pdf">Steven Logreira, IBM - Linux on S/390 Mainframe</A>
</TD></TR><TR><TD>
<LI>February 3rd, 2001 -
</TD><TD>
<A HREF="/members/tanner">Bob Tanner - SMTP Auth, ORBS, MAPS</A>
</TD></TR><TR><TD>
<LI>December 4th, 1999 -
</TD><TD>
<A HREF="pastnotes/lrp_intro.html">Joel Schneider - The Linux Router Project</A>
</TD></TR></TABLE>
</CENTER>
