<UL>
<LI><B>Sunday, February 4th, 2001</B></LI>
<blockquote>
Yesterday's TCLUG meeting went really well with over 35 members attending. If you missed it, Bob's presentation can be found here: <A HREF="http://www.mn-linux.org/members/tanner/">http://www.mn-linux.org/members/tanner/</A>
</blockquote>

<LI><B>Wednesday, January 31st, 2001</B></LI>
<blockquote>
I did an overhaul of the TCLUG web pages. The old look was terrible. (Why didn't someone say something?) Let me know what you think by voting on the <A HREF="/">top-level page</A>.
</blockquote>

<LI><B>Saturday, January 20th, 2001</B></LI>
<blockquote>
The next TCLUG beer meeting is scheduled for Thursday, January 25th. Go <A HREF="/beermeeting/">here for more info.</A>
</blockquote>
<LI><b>Saturday, November 11, 2000</b></LI>
<blockquote>Filesystems was the talk for the last TCLUG meeting.  Links to the various papers are listed below.  Note:  The XFS paper will be posted as soon as I receive it.
<br>
<br>In the meantime, check out:
<br>- Chad "^chewie" Walstrom's <a href="http://www.wookimus.net/lvm_cheat.html">LVM cheatsheet</a>
<br>- <a href="http://linux.msede.com/lvm/">Linux LVM</a> home page.
<br>
<br>- <a href="http://www.sistina.com/Pubs/miami2000_david_teigland.pdf">Dave Teigland's GFS paper</a>
<br>- <a href="http://www.sistina.com/Pages/miami2000_slides.html">Additional techical papers of interest from Sistina</a>.
</blockquote>

<LI><b>Monday, October 23, 2000</b></LI>
<blockquote>
The TCLUG now has a RedHat/Debian/Slackware mirror. Just go to <A HREF="ftp://ftp.mn-linux.org/linux/">ftp://ftp.mn-linux.org/linux/</A>. Thanks again to <A HREF="http://www.real-time.com">Real-Time</a>.
</blockquote>
</UL>
