<TABLE BORDER=0>
<TR><TD>
<form method="get" action="http://search.mn-linux.org/search.php">
<input type=hidden name=ps value=10>
<input type=hidden name=o value=0>
<input type=hidden name=m value=and>
<input type=hidden name=ul value="/www.mn-linux.org/">
<input type=hidden name=t value="">
Search TCLUG website:
</TD><TD>
<input type="text" size="15" name="words" value="">
<FONT SIZE=-1>
<a href="/search.html">Advanced</a>
</FONT>
</form>
</TD></TR>
<TR><TD>
<form method="get" action="http://search.mn-linux.org/search.php">
<input type=hidden name=ps value=10>
<input type=hidden name=o value=0>
<input type=hidden name=m value=and>
<input type=hidden name=ul value=/tclug-list/>
<input type=hidden name=t value="">
Search TCLUG Mailing List:
</TD><TD>
<input type="text" size="15" name="q" value="">
<FONT SIZE=-1>
<a href="http://search.mn-linux.org/tclug-list/">Advanced</a>
</FONT>
</form>
</TD></TR>
<TR><TD>
<form method="get" action="http://search.mn-linux.org/search.php">
<input type=hidden name=ps value=10>
<input type=hidden name=t value="">
<input type=hidden name=o value="0">
<input type=hidden name=m value="and">
<input type=hidden name=ul value="/linux-kernel/">
Search linux-kernel list
</TD><TD>
<input type="text" size="15" name="q" value="">
<FONT SIZE=-1>
<a href="http://mailman.real-time.com/linux-kernel">Advanced</a>
</FONT>
</form>
</TD></TR>
<TR><TD>

<form method=GET action=http://www.google.com/linux>
<input type=hidden name=num value=30>
Search Linux Google
</TD><TD>
<INPUT type=text name=q size=15 maxlength=256 value="">
<FONT SIZE=-1>
<a href="http://www.google.com/linux">Advanced</a>
</FONT>
</TD></TR>
</TABLE>

